### ISSUE TITLE
加载composer包，未配置就开始报错了

### ISSUE THREAD

**Issue by MonkWang** [hyperf/metric#9]
composer require hyperf/metric，后未发布publish，启动系统就开始报错

[ERROR] TypeError: Argument 1 passed to Hyperf\Utils\Str::snake() must be of the type string, null given, called in /web/cunsite_msa/users-server/vendor/hyperf/metric/src/Adapter/Prometheus/MetricFactory.php on line 158(0) in /web/cunsite_msa/users-server/vendor/hyperf/utils/src/Str.php:630
Stack trace:
#0 /web/cunsite_msa/users-server/vendor/hyperf/metric/src/Adapter/Prometheus/MetricFactory.php(158): Hyperf\Utils\Str::snake()
#1 /web/cunsite_msa/users-server/vendor/hyperf/metric/src/Adapter/Prometheus/MetricFactory.php(84): Hyperf\Metric\Adapter\Prometheus\MetricFactory->getNamespace()
#2 /web/cunsite_msa/users-server/vendor/hyperf/metric/src/MetricSetter.php(49): Hyperf\Metric\Adapter\Prometheus\MetricFactory->makeGauge()
#3 /web/cunsite_msa/users-server/vendor/hyperf/metric/src/Listener/OnMetricFactoryReady.php(95): Hyperf\Metric\Listener\OnMetricFactoryReady->factoryMetrics()
#4 /web/cunsite_msa/users-server/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\Metric\Listener\OnMetricFactoryReady->process()
#5 /web/cunsite_msa/users-server/vendor/hyperf/metric/src/Process/MetricProcess.php(50): Hyperf\Event\EventDispatcher->dispatch()
#6 /web/cunsite_msa/users-server/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\Metric\Process\MetricProcess->handle()
#7 {main}

**Comment by limingxinleo** [comment]
composer info | grep hyperf
